name: Update Proxy Lists

on:
  schedule:
    - cron: '0 9,21 * * *'   # 00:00 и 12:00 МСК
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sources/sources.txt'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🚀 Run parser
        run: python blacklist_parser.py   # <-- ИСПРАВЛЕНО ИМЯ ФАЙЛА

      - name: 🔄 Update README with stats
        run: |
          TOTAL=$(jq -r .total public/stats.json)
          LAST_UPDATE=$(jq -r .last_update public/stats.json)
          LAST_UPDATE_URL=$(echo "$LAST_UPDATE" | sed 's/ /%20/g')
          sed -i "s|{{date}}|$LAST_UPDATE_URL|g" README.md
          sed -i "s|{{total_android}}|$TOTAL|g" README.md
          sed -i "s|{{last_update}}|$LAST_UPDATE|g" README.md
          git add README.md

      - name: 📊 Commit & Push changes
        run: |
          git config --global user.name "Kfg Bot"
          git config --global user.email "bot@kfg.example.com"
          git add public/sub.txt public/sub_ios.txt public/sub_singbox.json public/stats.json
          git commit -m "🔄 Update proxy lists $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push
